const { app, BrowserWindow, ipcMain, protocol, Menu, session, dialog } = require('electron');
const path = require('path');
const { execSync, spawn } = require('child_process');
const fs = require('fs');
const os = require('os');
const http = require('http');
const chokidar = require('chokidar');

const isDev = !app.isPackaged;

function findBinary(name, envVar, devPaths, prodRelative) {
  // 1. Check env variable
  const envPath = process.env[envVar];
  if (envPath && fs.existsSync(envPath)) return envPath;

  // 2. Production: bundled in resources
  if (!isDev) {
    const bundled = path.join(process.resourcesPath, prodRelative);
    if (fs.existsSync(bundled)) return bundled;
  }

  // 3. Dev: check common locations
  for (const p of devPaths) {
    if (fs.existsSync(p)) return p;
  }

  // 4. Fallback
  return devPaths[0] || name;
}

const YTDLP_PATH = findBinary('yt-dlp', 'YTDLP_PATH', [
  path.join(os.homedir(), 'AppData', 'Local', 'Programs', 'yt-dlp.exe'),
  'yt-dlp.exe',
], 'yt-dlp.exe');

const FFMPEG_PATH = findBinary('ffmpeg', 'FFMPEG_PATH', [
  path.join(os.homedir(), 'AppData', 'Local', 'Programs', 'ffmpeg', 'bin', 'ffmpeg.exe'),
  'ffmpeg.exe',
], 'ffmpeg');

const COOKIE_DIR = path.join(os.tmpdir(), 'spotilark-cookies');
const COOKIE_PATH = path.join(COOKIE_DIR, 'youtube-main.txt');

// Set env for Next.js server routes
process.env.YTDLP_PATH = YTDLP_PATH;
process.env.FFMPEG_PATH = FFMPEG_PATH;

let mainWindow;

function createWindow() {
  // Build a minimal menu with useful items (Reload, Force Reload, DevTools)
  const menuTemplate = [
    {
      label: 'File',
      submenu: [
        { label: 'Reload', accelerator: 'CmdOrCtrl+R', click: () => mainWindow?.webContents.reload() },
        { label: 'Force Reload', accelerator: 'CmdOrCtrl+Shift+R', click: () => mainWindow?.webContents.reloadIgnoringCache() },
        { type: 'separator' },
        { label: 'DevTools', accelerator: 'F12', click: () => mainWindow?.webContents.toggleDevTools() },
        { type: 'separator' },
        { role: 'quit' },
      ],
    },
    {
      label: 'View',
      submenu: [
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' },
        { type: 'separator' },
        { role: 'togglefullscreen' },
      ],
    },
  ];
  Menu.setApplicationMenu(Menu.buildFromTemplate(menuTemplate));

  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 1000,
    minHeight: 600,
    title: 'Spotilark',
    icon: path.join(__dirname, '../public/icon.png'),
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
    backgroundColor: '#000000',
  });

  if (isDev) {
    mainWindow.loadURL('http://localhost:9002');
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  } else {
    const PORT = 9100;
    const appDir = path.join(__dirname, '..');

    console.log(`[Electron] Starting Next.js server in production...`);
    const next = require(path.join(appDir, '.next', 'standalone', 'node_modules', 'next'));
    const nextApp = next({ dev: false, dir: appDir, quiet: true });
    const handle = nextApp.getRequestHandler();

    nextApp.prepare().then(() => {
      const server = http.createServer(handle);
      server.listen(PORT, '127.0.0.1', () => {
        console.log(`[Electron] Next.js server ready on port ${PORT}`);
        mainWindow.loadURL(`http://localhost:${PORT}`);
      });
      server.on('error', (err) => {
        console.error('[Electron] Server error:', err.message);
        mainWindow.loadFile(path.join(__dirname, '../out/index.html'));
      });
    }).catch((err) => {
      console.error('[Electron] Failed to start Next.js:', err.message);
      mainWindow.loadFile(path.join(__dirname, '../out/index.html'));
    });
  }

  mainWindow.on('closed', () => { mainWindow = null; });
}

// --- IPC Handlers ---

// Window controls
ipcMain.handle('window-minimize', () => mainWindow?.minimize());
ipcMain.handle('window-maximize', () => {
  if (mainWindow?.isMaximized()) mainWindow.unmaximize();
  else mainWindow?.maximize();
});
ipcMain.handle('window-close', () => mainWindow?.close());
ipcMain.handle('window-is-maximized', () => mainWindow?.isMaximized() || false);

// --- YouTube Cookie Auth ---
function cookiesToNetscape(cookies) {
  let lines = ['# Netscape HTTP Cookie File', '# This file was generated by Spotilark', ''];
  for (const c of cookies) {
    const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
    const flag = 'TRUE';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires = c.expirationDate ? Math.floor(c.expirationDate) : 0;
    lines.push(`${domain}\t${flag}\t${c.path}\t${secure}\t${expires}\t${c.name}\t${c.value}`);
  }
  return lines.join('\n');
}

ipcMain.handle('yt-login-youtube', async () => {
  return new Promise((resolve) => {
    const loginWindow = new BrowserWindow({
      width: 800,
      height: 700,
      parent: mainWindow,
      modal: true,
      title: 'Sign in to YouTube',
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
      },
    });

    loginWindow.loadURL('https://accounts.google.com/ServiceLogin?service=youtube&continue=https://www.youtube.com');

    let resolved = false;

    const checkAndClose = async () => {
      if (resolved) return;
      try {
        const url = loginWindow.webContents.getURL();
        if (url.includes('youtube.com') && !url.includes('accounts.google.com')) {
          resolved = true;
          const cookies = await loginWindow.webContents.session.cookies.get({ domain: '.youtube.com' });
          const googleCookies = await loginWindow.webContents.session.cookies.get({ domain: '.google.com' });
          const allCookies = [...cookies, ...googleCookies];

          if (allCookies.length > 0) {
            fs.mkdirSync(COOKIE_DIR, { recursive: true });
            fs.writeFileSync(COOKIE_PATH, cookiesToNetscape(allCookies));
            console.log(`[YouTube Auth] Saved ${allCookies.length} cookies to ${COOKIE_PATH}`);
            loginWindow.close();
            resolve({ success: true, cookieCount: allCookies.length });
          } else {
            loginWindow.close();
            resolve({ success: false, error: 'No cookies found after login' });
          }
        }
      } catch {}
    };

    loginWindow.webContents.on('did-navigate', checkAndClose);
    loginWindow.webContents.on('did-navigate-in-page', checkAndClose);

    loginWindow.on('closed', () => {
      if (!resolved) {
        resolved = true;
        resolve({ success: false, error: 'Window closed without login' });
      }
    });
  });
});

ipcMain.handle('yt-logout-youtube', () => {
  try {
    if (fs.existsSync(COOKIE_PATH)) {
      fs.unlinkSync(COOKIE_PATH);
      console.log('[YouTube Auth] Cookies deleted');
    }
  } catch {}
  return { success: true };
});

ipcMain.handle('yt-auth-status', () => {
  const exists = fs.existsSync(COOKIE_PATH);
  return { authenticated: exists };
});

// Get cookie args for yt-dlp CLI
function getYtDlpCookieArgs() {
  if (fs.existsSync(COOKIE_PATH)) {
    return `--cookies "${COOKIE_PATH}"`;
  }
  return '';
}

// yt-dlp search
ipcMain.handle('yt-search', async (_, query) => {
  try {
    const cookieArgs = getYtDlpCookieArgs();
    const result = execSync(
      `"${YTDLP_PATH}" ${cookieArgs} --flat-playlist --dump-single-json --no-warnings "ytsearch20:${query}"`,
      { timeout: 30000, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
    );
    const data = JSON.parse(result);
    const entries = data.entries || [];
    return entries
      .filter(e => e.id && e.title)
      .map(e => ({
        id: e.id,
        title: e.title,
        channel: e.channel || e.uploader || 'Unknown',
        duration: e.duration || 0,
        thumbnail: e.thumbnails?.[0]?.url || `https://i.ytimg.com/vi/${e.id}/mqdefault.jpg`,
      }));
  } catch (e) {
    console.error('yt-search failed:', e.message);
    return [];
  }
});

// yt-dlp stream URL
ipcMain.handle('yt-get-stream-url', async (_, videoId) => {
  try {
    const cookieArgs = getYtDlpCookieArgs();
    const result = execSync(
      `"${YTDLP_PATH}" ${cookieArgs} --get-url -f "bestaudio[ext=m4a]/bestaudio[ext=mp3]/bestaudio" --no-warnings "https://www.youtube.com/watch?v=${videoId}"`,
      { timeout: 30000, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
    );
    return result.trim();
  } catch (e) {
    console.error('yt-get-stream-url failed:', e.message);
    return null;
  }
});

// yt-dlp download
ipcMain.handle('yt-download', async (_, { videoId, format }) => {
  const downloadDir = path.join(app.getPath('userData'), 'downloads');
  fs.mkdirSync(downloadDir, { recursive: true });

  const outputTemplate = path.join(downloadDir, `${videoId}.%(ext)s`);
  const isAudio = format === 'audio';
  const cookieArgs = getYtDlpCookieArgs();

  try {
    const ffmpegArg = fs.existsSync(FFMPEG_PATH) ? `--ffmpeg-location "${FFMPEG_PATH}"` : '';
    execSync(
      `"${YTDLP_PATH}" ${cookieArgs} ${ffmpegArg} ${isAudio ? '-x --audio-format mp3 --audio-quality 0' : '-f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best --merge-output-format mp4'} -o "${outputTemplate}" --no-warnings "https://www.youtube.com/watch?v=${videoId}"`,
      { timeout: 120000, stdio: 'pipe' }
    );

    const files = fs.readdirSync(downloadDir).filter(f => f.startsWith(videoId));
    if (files.length > 0) {
      return path.join(downloadDir, files[0]);
    }
  } catch (e) {
    console.error('yt-download failed:', e.message);
  }
  return null;
});

// --- Path Security ---

const ALLOWED_FS_DIRS = [
  app.getPath('userData'),
  app.getPath('downloads'),
  app.getPath('music'),
  app.getPath('temp'),
  path.join(os.homedir(), '.spotilark'),
];

function isPathAllowed(targetPath) {
  const resolved = path.resolve(targetPath);
  const normalizedResolved = resolved.replace(/\\/g, '/').toLowerCase();
  return ALLOWED_FS_DIRS.some(dir => {
    const normalizedDir = path.resolve(dir).replace(/\\/g, '/').toLowerCase();
    return normalizedResolved.startsWith(normalizedDir + '/') || normalizedResolved === normalizedDir;
  });
}

function rejectUnsafePath(targetPath) {
  if (targetPath && (targetPath.includes('..') || targetPath.includes('\0'))) {
    return true;
  }
  return !isPathAllowed(targetPath);
}

// File system access
ipcMain.handle('fs-read-file', async (_, filePath) => {
  if (rejectUnsafePath(filePath)) {
    console.warn(`[Security] Blocked fs-read-file: ${filePath}`);
    throw new Error('Access denied: path outside allowed directories');
  }
  return fs.readFileSync(filePath);
});

ipcMain.handle('fs-read-dir', async (_, dirPath) => {
  if (rejectUnsafePath(dirPath)) {
    console.warn(`[Security] Blocked fs-read-dir: ${dirPath}`);
    throw new Error('Access denied: path outside allowed directories');
  }
  return fs.readdirSync(dirPath, { withFileTypes: true });
});

ipcMain.handle('fs-exists', async (_, filePath) => {
  if (rejectUnsafePath(filePath)) {
    return false;
  }
  return fs.existsSync(filePath);
});

ipcMain.handle('fs-write-file', async (_, filePath, data) => {
  if (rejectUnsafePath(filePath)) {
    console.warn(`[Security] Blocked fs-write-file: ${filePath}`);
    throw new Error('Access denied: path outside allowed directories');
  }
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, data);
  return true;
});

ipcMain.handle('fs-mkdir', async (_, dirPath) => {
  if (rejectUnsafePath(dirPath)) {
    console.warn(`[Security] Blocked fs-mkdir: ${dirPath}`);
    throw new Error('Access denied: path outside allowed directories');
  }
  if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath, { recursive: true });
  return true;
});

// App paths
ipcMain.handle('get-paths', () => ({
  userData: app.getPath('userData'),
  downloads: app.getPath('downloads'),
  music: app.getPath('music'),
  home: app.getPath('home'),
}));

// --- Folder Scanning & Watching ---

const AUDIO_EXTENSIONS = new Set(['.mp3', '.m4a', '.flac', '.wav', '.ogg', '.aac', '.opus', '.wma', '.mp4', '.webm', '.mkv']);
const watchedFolders = new Map();

function scanFolderRecursive(dirPath, maxDepth = 5, currentDepth = 0) {
  const results = [];
  if (currentDepth > maxDepth) return results;
  try {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name.startsWith('.')) continue;
      const fullPath = path.join(dirPath, entry.name);
      if (entry.isDirectory()) {
        results.push(...scanFolderRecursive(fullPath, maxDepth, currentDepth + 1));
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name).toLowerCase();
        if (AUDIO_EXTENSIONS.has(ext)) {
          try {
            const stat = fs.statSync(fullPath);
            results.push({
              path: fullPath,
              name: entry.name,
              size: stat.size,
              modified: stat.mtime.toISOString(),
            });
          } catch {}
        }
      }
    }
  } catch {}
  return results;
}

ipcMain.handle('dialog-select-folder', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    properties: ['openDirectory'],
    title: 'Select Music Folder',
  });
  if (result.canceled || result.filePaths.length === 0) return null;
  return result.filePaths[0];
});

ipcMain.handle('fs-scan-folder', async (_, folderPath) => {
  console.log(`[Electron] Scanning folder: ${folderPath}`);
  const files = scanFolderRecursive(folderPath);
  console.log(`[Electron] Found ${files.length} audio files in ${folderPath}`);
  return files;
});

ipcMain.handle('folder-watch-start', async (_, folderPath) => {
  if (watchedFolders.has(folderPath)) return { success: true, alreadyWatching: true };

  const watcher = chokidar.watch(folderPath, {
    ignored: /(^|[\/\\])\.(?!spotilark)|node_modules/,
    persistent: true,
    ignoreInitial: true,
    depth: 5,
    awaitWriteFinish: { stabilityThreshold: 500, pollInterval: 100 },
  });

  const sendEvent = (type, filePath) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('folder-watch-event', {
        type,
        path: filePath,
        folder: folderPath,
        timestamp: Date.now(),
      });
    }
  };

  watcher
    .on('add', (p) => {
      const ext = path.extname(p).toLowerCase();
      if (AUDIO_EXTENSIONS.has(ext)) sendEvent('add', p);
    })
    .on('change', (p) => {
      const ext = path.extname(p).toLowerCase();
      if (AUDIO_EXTENSIONS.has(ext)) sendEvent('change', p);
    })
    .on('unlink', (p) => {
      const ext = path.extname(p).toLowerCase();
      if (AUDIO_EXTENSIONS.has(ext)) sendEvent('unlink', p);
    });

  watchedFolders.set(folderPath, watcher);
  console.log(`[Electron] Started watching: ${folderPath}`);
  return { success: true };
});

ipcMain.handle('folder-watch-stop', async (_, folderPath) => {
  const watcher = watchedFolders.get(folderPath);
  if (watcher) {
    await watcher.close();
    watchedFolders.delete(folderPath);
    console.log(`[Electron] Stopped watching: ${folderPath}`);
  }
  return { success: true };
});

ipcMain.handle('folder-watch-list', () => {
  return Array.from(watchedFolders.keys());
});

// --- App Lifecycle ---
app.whenReady().then(() => {
  protocol.registerFileProtocol('local-audio', (request, callback) => {
    const filePath = decodeURIComponent(request.url.replace('local-audio://', ''));
    callback({ path: filePath });
  });

  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
